= Tutorial Applications

== About

The tutorial are learning materials that help you to learn TERASOLUNA Batch Framework for Java (5.x) (https://terasoluna-batch.github.io/[https://terasoluna-batch.github.io/]).

The tutorial consists of

1. Development Guideline
2. Completed tutorial applications(this repository)

== Getting started
* If you would like to try tutorials,
    Go to https://terasoluna-batch.github.io/guideline/5.5.0.RELEASE/ja/single_index.html#Ch09[Tutorial] and follow the tutorial instructions explained in Development Guideline.
* If you would like to access completed,
    Please download completed tutorials in this repository. See next section about how to get.

== How to get completed tutorials
* Get it in one of the following ways:
** Download as archived files
    1. Go to the https://github.com/terasoluna-batch/v5-tutorial/releases/tag/5.5.0.RELEASE[tag/5.5.0.RELEASE] page.
    2. Download zip or tar.gz files and unzip it.
** Fork or checkout Refer release tags such as ``5.5.0.RELEASE``.

* Copy the configraion files to the ``src/main`` directory.
** Execute the following command in the ``terasoluna-batch-tutorial`` directory.

==== For Java Config
```console
$ cp -R src/append/javaconfig/* src/main/
```

==== For XML Config
```console
$ cp -R src/append/xmlconfig/* src/main/
```

* Remove unnecessary directories.
** Execute the following command in the ``terasoluna-batch-tutorial`` directory.

```console
$ rm -rf src/append
```

=== Build

Make sure the project builds successfully. Execute the following command in the ``terasoluna-batch-tutorial`` directory.

```console
$ mvn clean package
```
